### ISSUE TITLE
When there is no image, the user should be able to see a placeholder image.

### ISSUE THREAD

**Issue by lflachs** [duranSofia/EatWise-React-Project#23]
When there is no image, the user should be able to see a placeholder image.
<img width="302" alt="Screenshot 2020-11-15 at 13 58 56" src="https://user-images.githubusercontent.com/26345843/99185547-da644680-274a-11eb-8b41-a5c8d19c2ca9.png">

You can use onError https://www.w3schools.com/Jsref/event_onerror.asp or you can put a ternary operator ;)

_Originally posted by @lflachs in https://github.com/secondreact/eatwise/issues/19#issuecomment-727566857_

**Comment by lflachs** [comment]
Same for the nutriments, if there is no nutriments, that could be great to see a text instead of empty values, why not for example inviting the users to submit the information themselves on openfoodfact?  

<img width="246" alt="Screenshot 2020-11-15 at 14 06 37" src="https://user-images.githubusercontent.com/26345843/99185698-d258d680-274b-11eb-8132-ee351c08e2ae.png">

**Comment by secondreact** [comment]
I am working on this issue. I have fixed the image and now I have to define what to put in the nutrient facts when there's no data.
